---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r echo=TRUE}
activity <- read.csv("~/GitHub/RepData_PeerAssessment1/activity/activity.csv")
# Convert to wide format
activityw <- reshape(activity, direction="wide", timevar="interval", idvar="date", v.names="steps")
# Make the column names equal to the times
colnames(activityw)[-1] <- substring(colnames(activityw)[-1],7)
```

## What is mean total number of steps taken per day?

```{r echo=TRUE}
daysumsw <- rowSums(activityw[,-1], na.rm=TRUE)
hist(daysumsw,breaks=seq(0,25000,by=1000), main="Histogram of Daily Steps",  xlab="Steps")

daysums <- aggregate(activity[,"steps"], by=list(date=activity$date), FUN=sum, na.rm=TRUE)
hist(daysums$x,breaks=seq(0,25000,by=1000), main="Histogram of Daily Steps", xlab="Steps")

cat("The mean number of steps per day is ",round(mean(daysums$x, na.rm=TRUE)),".\n", sep="")
cat("The median number of steps per day is ",round(median(daysums$x, na.rm=TRUE)),".\n", sep="")
```

## What is the average daily activity pattern?

```{r echo=TRUE}
timemeansw <- colMeans(activityw[,-1], na.rm=TRUE)
# Calculate times in decimal hours and then do the plot.
dectimesw <- 100 * (as.numeric(names(timemeansw)) %/% 100 + as.numeric(names(timemeansw)) %% 100 / 60)
plot(dectimesw, timemeansw, type="l", xlab="Interval", ylab="Number of Steps", main=" Average Daily Activity Pattern")

timemeans <- aggregate(activity[,"steps"], by=list(interval=activity$interval), FUN=mean, na.rm=TRUE)
timemeans$dectime <- 100 * (timemeans$interval %/% 100 + timemeans$interval %% 100 / 60)
plot(timemeans$dectime, timemeans$x, type="l", xlab="Interval", ylab="Number of Steps", main=" Average Daily Activity Pattern")

cat("The maximum occurs in the interval starting at ",timemeans$interval[which.max(timemeans$x)],".\n",sep="")
```

## Imputing missing values

```{r echo=TRUE}
cat("The dataset had ",sum(is.na(activity$steps)), " rows with missing values.\n", sep="")

# Create a column with NAs replaced with the mean for that time.
activity$stepsi <- ifelse(is.na(activity$steps),timemeans$x[match(activity$interval,timemeans$interval)],activity$steps)

# Calculate the day totals again.
daysumsi <- aggregate(activity[,"stepsi"], by=list(date=activity$date), FUN=sum, na.rm=TRUE)
hist(daysumsi$x,breaks=seq(0,25000,by=1000), main="Histogram of Daily Steps (after imputation", xlab="Steps")

cat("The mean number of steps per day is now ",round(mean(daysumsi$x, na.rm=TRUE))," rather than ",round(mean(daysums$x, na.rm=TRUE)),".\n", sep="")
cat("The median number of steps per day is now ",round(median(daysumsi$x, na.rm=TRUE))," rather than ",round(median(daysums$x, na.rm=TRUE)),".\n", sep="")
cat("The total number of steps has",ifelse(sum(daysumsi$x, na.rm=TRUE) > sum(daysums$x, na.rm=TRUE),"increased.","decreased."))
```

## Are there differences in activity patterns between weekdays and weekends?

```{r echo=TRUE}
#Calculate a vector of day names.
activity$day <- weekdays(as.Date(activity$date,format="%Y-%m-%d"))
#Calculate a vector of booleans indicating weekend days.
activity$daytype <- as.factor(ifelse((activity$day == "Saturday") | (activity$day == "Sunday"),"weekend","weekday"))

#Caclculate the interval means for each day type (weekday or weekend).
timemeansi <- aggregate(activity[,"stepsi"], by=list(interval=activity$interval,daytype=activity$daytype), FUN=mean, na.rm=TRUE)
timemeansi$dectime <- 100 * (timemeansi$interval %/% 100 + timemeansi$interval %% 100 / 60)

library(lattice)
xyplot(x~dectime|daytype, data=timemeansi, type="l", xlab="Interval", ylab="Number of steps",layout=c(1,2), ylim=c(0,250))
```